-- Supabase setup
-- 1) Open Supabase SQL Editor and run this file.
-- 2) Then create a Storage bucket named "posts" and make it PUBLIC.

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  caption text not null,
  image_url text not null,
  created_at timestamptz not null default now()
);

alter table public.posts enable row level security;

-- The website reads through the server using the service-role key.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY in client-side code.

create policy "public can read posts"
on public.posts for select
to anon, authenticated
using (true);
